#pragma once

using TestFn = void (*)();

struct TestCase {
    const char* name;
    TestFn run;
};

void test_hex_roundtrip();
void test_hex_invalid_input();
void test_hex_normalize_input();
void test_hex_editor_cursor_normalize();
void test_crc_known_vectors();
void test_config_external_reload_state();
void test_script_controls_snapshot();
void test_script_on_open_log();
void test_script_on_close_log();
void test_script_on_error_log();
void test_script_multi_dock_snapshot();
void test_script_dock_layout_fields();
void test_script_table_layout_snapshot();
void test_script_crc_bridge();
void test_script_read_version_flow();
void test_script_read_version_split_flow();
void test_script_timeout_flow();
void test_luals_api_sync_contains_tx_and_dialog_api();
void test_script_missing_callbacks_allowed();
void test_script_invalid_controls_fail();
void test_script_invalid_dock_anchor_fail();
void test_script_table_layout_unknown_control_fail();
void test_script_table_layout_duplicate_control_fail();
void test_script_table_layout_missing_control_fail();
void test_script_table_layout_row_overflow_fail();
void test_script_runtime_error_logged();
void test_protocol_directory_reload();
void test_config_default_roundtrip();
void test_config_logging_roundtrip();
void test_config_default_script_workspace();
void test_protocol_scan_and_root_roundtrip();
void test_dock_log_and_script_split();
void test_dock_receive_row_single_line_hex_and_ascii();
void test_dock_receive_row_single_line_message_and_timestamp();
void test_lua_dock_layout_key_uses_protocol_and_script();
void test_lua_dock_layout_key_falls_back_to_script_directory();
void test_lua_dock_layout_paths_prefer_user_layout();
void test_lua_dock_layout_paths_detect_legacy_source();
void test_lua_dock_layout_meta_path_is_sibling_yaml();
void test_lua_dock_layout_meta_schema_v2_marks_modern_layout();
void test_lua_dock_layout_meta_schema_v3_marks_modern_layout();
void test_lua_dock_layout_meta_read_failure_falls_back_to_legacy();
void test_lua_dock_layout_dock_id_sharing_does_not_mark_modern_legacy();
void test_lua_dock_window_name_keeps_stable_id();
void test_lua_dock_layout_requests_group_tabs();
void test_lua_dock_settings_filter_keeps_current_protocol_windows();
void test_lua_dock_settings_filter_keeps_current_windows_without_active_docks();
void test_lua_dock_settings_filter_keeps_same_dock_id_tab_stack();
void test_workspace_layout_mode_after_load_prefers_default_build_only_when_missing();
void test_protocol_workspace_switch_decision_uses_draft_only_until_reload();
void test_protocol_workspace_switch_decision_reloads_draft_when_clicked();
void test_protocol_switch_resets_lua_default_dock_state_only_when_changed();
void test_lua_default_dock_layout_runs_only_during_default_build();
void test_plot_history_trim_and_envelope();
void test_wave_layout_solver_clamps_without_overflow();
void test_plot_limited_envelope_preserves_spikes();
void test_plot_low_density_envelope_keeps_single_value_line();
void test_plot_cursor_snap_and_delta();
void test_plot_cursor_snap_by_time_and_measurement();
void test_wave_cursor_smart_snap_edge();
void test_wave_cursor_smart_snap_extreme();
void test_wave_cursor_smart_snap_fallback_to_nearest();
void test_wave_cursor_drag_time_uses_smart_snap();
void test_plot_channel_scale_and_offset_apply_to_display_only();
void test_plot_cursor_snap_scope_selection();
void test_plot_limited_envelope_edges();
void test_wave_frequency_parse_and_axis_mapping();
void test_wave_viewport_zoom_modes_and_clamp();
void test_wave_overview_viewport_normalize();
void test_wave_cursor_position_in_viewport();
void test_wave_cursor_interval_text_by_axis();
void test_wave_cursor_interval_lock();
void test_tcp_transport_roundtrip();
void test_transport_enqueue_send_async_roundtrip();
void test_tcp_server_connection_takeover_replaces_active_client();
void test_serial_transport_error_path();
void test_serial_port_name_normalization();
void test_application_tcp_lua_read_version_roundtrip();
void test_application_lua_controls_without_connection();
void test_application_failed_protocol_reload_keeps_previous_runtime();
void test_application_open_transport_uses_serial_runtime_config();
void test_application_logging_filters_script_and_host();

const TestCase* allTests();
int testCount();
