set(PROTOSCOPE_VERSION_CURRENT_TAG "")
set(PROTOSCOPE_VERSION_BASE_TAG "")
set(PROTOSCOPE_VERSION_COMMIT_SHA "")
set(PROTOSCOPE_VERSION_IS_EXACT_TAG false)

find_package(Git QUIET)
if(Git_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short=7 HEAD
        WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
        RESULT_VARIABLE PROTOSCOPE_GIT_SHA_RESULT
        OUTPUT_VARIABLE PROTOSCOPE_VERSION_COMMIT_SHA
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT PROTOSCOPE_GIT_SHA_RESULT EQUAL 0)
        set(PROTOSCOPE_VERSION_COMMIT_SHA "")
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" describe --exact-match --tags --match "v[0-9]*.[0-9]*.[0-9]*" HEAD
        WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
        RESULT_VARIABLE PROTOSCOPE_GIT_CURRENT_TAG_RESULT
        OUTPUT_VARIABLE PROTOSCOPE_VERSION_CURRENT_TAG
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT PROTOSCOPE_GIT_CURRENT_TAG_RESULT EQUAL 0)
        set(PROTOSCOPE_VERSION_CURRENT_TAG "")
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*.[0-9]*" HEAD
        WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
        RESULT_VARIABLE PROTOSCOPE_GIT_BASE_TAG_RESULT
        OUTPUT_VARIABLE PROTOSCOPE_VERSION_BASE_TAG
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT PROTOSCOPE_GIT_BASE_TAG_RESULT EQUAL 0)
        set(PROTOSCOPE_VERSION_BASE_TAG "")
    endif()
endif()

if(PROTOSCOPE_VERSION_CURRENT_TAG)
    set(PROTOSCOPE_VERSION_STRING "${PROTOSCOPE_VERSION_CURRENT_TAG}")
    set(PROTOSCOPE_VERSION_IS_EXACT_TAG true)
elseif(PROTOSCOPE_VERSION_BASE_TAG AND PROTOSCOPE_VERSION_COMMIT_SHA)
    set(PROTOSCOPE_VERSION_STRING "${PROTOSCOPE_VERSION_BASE_TAG}+${PROTOSCOPE_VERSION_COMMIT_SHA}")
elseif(PROTOSCOPE_VERSION_COMMIT_SHA)
    set(PROTOSCOPE_VERSION_STRING "${PROTOSCOPE_VERSION_COMMIT_SHA}")
else()
    set(PROTOSCOPE_VERSION_STRING "unknown")
endif()

configure_file(
    "${PROJECT_SOURCE_DIR}/cmake/version.hpp.in"
    "${PROJECT_BINARY_DIR}/generated/include/protoscope/build/version.hpp"
    @ONLY
)
